[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "playlist-evaluator"
version = "0.1.0"
description = "Scores playlists for alignment/cohesion/humor"
requires-python = ">=3.10"
dependencies = ["pydantic>=2.6"]

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = ["pytest", "black"]