[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "playlist-genai"
version = "0.1.0"
description = "LLM-generated playlist builder + benchmarks"
requires-python = ">=3.10"
dependencies = [
  "openai>=1.0.0",
  "requests>=2.32.0",
  "python-dotenv>=1.0.0",
  "tqdm>=4.0.0",
]

[project.optional-dependencies]
dev = ["pytest", "black"]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
playlist-openai-bench = "openai_api_async_main:main"
playlist-ollama-bench = "benchmark_main:main"
